name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Please use this form to file new bugs!
  - type: input
    id: contact
    attributes:
      label: Who discovered this?
      description: Was it something you found or are you filing for someone else? If someone else, how can we contact them?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
- type: textarea
    id: page
    attributes:
      label: What pages did this appear on?
      description: please include URLs of where you saw the bug
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      required: false
 - type: markdown
    attributes:
      value: |
        Please add screenshots to the comments of this initial issue.
