name: "Bug Report"
description: "Use this template to file a bug report"
title: "Bug: [Brief description of the bug]"

labels:
  - "Type: Bug"

body:
  - type: markdown
    attributes:
      value: |
        Please use this form to file new bugs! Add screenshots to the comments of this initial form.
  - type: input
    id: contact
    attributes:
      label: Who discovered this?
      description: Was it something you found or are you filing for someone else? If someone else, how can we contact them?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment did you experience the bug?
      options:
        - staging 
        - demo
        - production
    validations:
      required: true- type: textarea
    id: page
    attributes:
      label: What pages did this appear on?
      description: please include URLs of where you saw the bug
    validations:
      required: true
  - type: textarea
    id: reproSteps
    attributes:
      label: "Detail the steps for someone to reproduce"
      description: "Reproduction steps"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    
