name: "QA Checklist"
description: "Use this template to manually QA for prod push"
title: "QA for prod push: Admin #[insert PR number], API #[insert PR number], Utils #[insert PR number]"

body:
- type: checkboxes
  id: Logging in
  attributes:
    description: Log In
    options:
      - label: notify-staging.app.cloud.gov resolves
      - label: Clicking sign in takes you to login page
      - label: 2FA code is sent promptly
      - label: 2FA code input screen appears as expected
      - label: After code is entered, you are brought to the “choose service” screen
      - label: Choosing a service brings you to the dashboard for that service
      
    
  

