name: "QA Checklist"
description: "Use this template to manually QA for prod push"
title: "QA checklist for production release: [insert planned release date here]"

body:
- type: checkboxes
  id: sign_in
  attributes:
    label: Sign In
    options:
      - label: notify-staging.app.cloud.gov resolves
      - label: Clicking sign in takes you to Login.gov
      - label: Can sign in via Login.gov
      - label: After successful login, you are brought to the “choose service” screen
      - label: Choosing a service brings you to the dashboard for that service

- type: checkboxes
  id: send_template
  attributes:
    label: Create a template and send
    options:
      - label: Clicking “Send messages” brings you to templates page
      - label: When “Create a template” button is clicked, the option to create new or copy existing template appears
      - label: Uploading a csv is quick and automatically directs you to the preview/send page
      - label: Formatting looks clean and in place
      - label: Message dashboard populates and shows “pending” until call is made to AWS for delivery receipt

- type: checkboxes
  id: send_copied_template
  attributes:
    label: Send a message from copied template
    options:
      - label: When “Create a template” button is clicked, the option to create new or copy existing template appears
      - label: Clicking “copy an existing template” allows you to choose from pre-existing template
      - label: After editing, the new template saves and you prepare to send


- type: checkboxes
  id: send_existing_template
  attributes:
    label: Send a message from existing template
    options:
      - label: Clicking on existing template brings you to preview screen with `prepare to send` button
      - label: All else above persists as true (formatting, send, dashboard, etc)

- type: checkboxes
  id: template_folder_permissions
  attributes:
    label: Checking template folder permissions
    options:
      - label: Only the template creator and platform admins should be able to see a new template
      - label: Adding a non platform admin user to a folder should grant them access to see the templates
      - label: Removing a non platform admin user to a folder should remove their access to see the templates
      - label: Platform admins should not be able to be added or removed from template folders, since they have full access regardless

- type: checkboxes
  id: download_reports
  attributes:
    label: Download the CSV delivery reports
    options:
      - label: Clicking on the CSV download directly after a message send downloads a report that contains the data we expect
      - label: Clicking on the CSV download links from the main dashboard downloads a report that contains the data we expect
      - label: The daily generated batch reports appear at the bottom of the main dashboard batch table with accurate information
      - label: The daily generated batch report buttons are highlighted appropriately based on which reports are available (1, 3, 5, and 7 day)
      - label: Downloading the generated batch reports that are available work properly and contain the data that we expect

- type: checkboxes
  id: invite_member
  attributes:
    label: Invite a team member
    options:
      - label: Clicking on “Team” in settings  brings you to team member screen
      - label: Clicking “Invite a team member” brings you to email and permissions screen
      - label: Clicking invite team member sends an invite and shows confirmation
      - label: Invite email provides live link that works to register new team member

- type: checkboxes
  id: delete_member
  attributes:
    label: Delete a team member
    options:
      - label: From team member screen, clicking “Change Details” on a specific profile brings you to that person’s profile
      - label: Clicking on “Remove this team member” prompts a confirmation
      - label: Clicking the confirmation removes the team member

- type: checkboxes
  id: sign_out
  attributes:
    label: Sign Out
    options:
      - label: Clicking “Sign Out” takes you back to the homepage and logs you out
