from flask import Blueprint

main = Blueprint("main", __name__)

from app.main.views import (  # noqa isort:skip
    add_service,
    api_keys,
    choose_account,
    code_not_received,
    conversation,
    dashboard,
    email_branding,
    feedback,
    find_services,
    find_users,
    forgot_password,
    history,
    inbound_number,
    index,
    invites,
    jobs,
    manage_users,
    new_password,
    notifications,
    organizations,
    performance,
    platform_admin,
    pricing,
    register,
    security_policy,
    send,
    service_settings,
    sign_in,
    sign_out,
    templates,
    tour,
    two_factor,
    uploads,
    user_profile,
    verify,
)
