ALL = (
    ("al'iraq", "Iraq"),
    ("aljazā'ir", "Algeria"),
    ("amelikahuipu'ia", "United States"),
    ("cote d'ivoire", "Ivory Coast"),
    ("coted'ivoire", "Ivory Coast"),
    ("democratic people's republic of koread", "North Korea"),
    ("democraticpeople'srepublicofkoread", "North Korea"),
    ("ityop'ia", "Ethiopia"),
    ("lao people's democratic republic", "Laos"),
    ("laopeople'sdemocraticrepublic", "Laos"),
    ("o'zbekstan", "Uzbekistan"),
    ("people's democratic republic of algeriaalgerie", "Algeria"),
    ("people's republic of bangladesh", "Bangladesh"),
    ("people's republic of china", "China"),
    ("people'sdemocraticrepublicofalgeriaalgerie", "Algeria"),
    ("people'srepublicofbangladesh", "Bangladesh"),
    ("people'srepublicofchina", "China"),
    ("republic of cote d'ivoire", "Ivory Coast"),
    ("republicofcoted'ivoire", "Ivory Coast"),
    ("sak'art'velo", "Georgia"),
    ("socialist people's libyan arab", "Libya"),
    ("socialistpeople'slibyanarab", "Libya"),
    ("the democratic people's republic of korea", "North Korea"),
    ("the lao people's democratic republic", "Laos"),
    ("the people's democratic republic of algeria", "Algeria"),
    ("the people's republic of bangladesh", "Bangladesh"),
    ("the people's republic of china", "China"),
    ("the republic of cote d'ivoire", "Ivory Coast"),
    ("thedemocraticpeople'srepublicofkorea", "North Korea"),
    ("thelaopeople'sdemocraticrepublic", "Laos"),
    ("thepeople'sdemocraticrepublicofalgeria", "Algeria"),
    ("thepeople'srepublicofbangladesh", "Bangladesh"),
    ("thepeople'srepublicofchina", "China"),
    ("therepublicofcoted'ivoire", "Ivory Coast"),
    ("timor lorosa'e", "East Timor"),
    ("timorlorosa'e", "East Timor"),
    ("yisra'el", "Israel"),
    ("\u200e", "Iraq"),
    ("aaland", "Åland Islands"),
    ("abudhabi", "Abu Dhabi"),
    ("abyssinia", "Ethiopia"),
    ("ad", "Andorra"),
    ("ae", "United Arab Emirates"),
    ("aeaj", "Ajman"),
    ("aeaz", "Abu Dhabi"),
    ("aedu", "Dubai"),
    ("aefu", "Fujairah"),
    ("aerk", "Ras al-Khaimah"),
    ("aeroes", "Faroe Islands"),
    ("aesh", "Sharjah"),
    ("aeuq", "Umm al-Quwain"),
    ("af", "Afghanistan"),
    ("afganastan", "Afghanistan"),
    ("afganestan", "Afghanistan"),
    ("afganhistan", "Afghanistan"),
    ("afganistan", "Afghanistan"),
    ("afghanestan", "Afghanistan"),
    ("afghanlstan", "Afghanistan"),
    ("afghistan", "Afghanistan"),
    ("aforika borwa", "South Africa"),
    ("aforikaborwa", "South Africa"),
    ("afrika borwa", "South Africa"),
    ("afrika dzonga", "South Africa"),
    ("afrikaborwa", "South Africa"),
    ("afrikadzonga", "South Africa"),
    ("afurika tshipembe", "South Africa"),
    ("afurikatshipembe", "South Africa"),
    ("ag", "Antigua and Barbuda"),
    ("agawec", "Mauritania"),
    ("ahvenanmaa", "Åland Islands"),
    ("ai", "Anguilla"),
    ("aigeria", "Algeria"),
    ("al itihaad al islamiya", "Somalia"),
    ("al", "Albania"),
    ("alabnia", "Albania"),
    ("aland", "Åland Islands"),
    ("albana", "Albania"),
    ("albanian", "Albania"),
    ("albanija", "Albania"),
    ("albaḥrayn", "Bahrain"),
    ("albenia", "Albania"),
    ("albiana", "Albania"),
    ("alegeria", "Algeria"),
    ("algeir", "Algeria"),
    ("algeirs", "Algeria"),
    ("algers", "Algeria"),
    ("algieria", "Algeria"),
    ("algiers", "Algeria"),
    ("alibania", "Albania"),
    ("aliraq", "Iraq"),
    ("alitihaad alislamiya", "Somalia"),
    ("alitihaadalislamiya", "Somalia"),
    ("almamlaka al‘arabiyyah as sa‘ūdiyyah", "Saudi Arabia"),
    ("almamlakaal‘arabiyyahassa‘ūdiyyah", "Saudi Arabia"),
    ("almaɣréb", "Morocco"),
    ("alyaman", "Yemen"),
    ("al’imārat al‘arabiyyah almuttaḥidah", "United Arab Emirates"),
    ("al’imāratal‘arabiyyahalmuttaḥidah", "United Arab Emirates"),
    ("al’urdun", "Jordan"),
    ("am", "Armenia"),
    ("ameeri", "United States"),
    ("ameica", "United States"),
    ("amerca", "United States"),
    ("amercia", "United States"),
    ("ameria", "United States"),
    ("america", "United States"),
    ("american virgin islands", "United States Virgin Islands"),
    ("americansamoa", "American Samoa"),
    ("americanvirginislands", "United States Virgin Islands"),
    ("americia", "United States"),
    ("amerika sāmoa", "Samoa"),
    ("amerikasāmoa", "Samoa"),
    ("amerruk", "Morocco"),
    ("amrica", "United States"),
    ("angolo", "Angola"),
    ("anmerica", "United States"),
    ("annam", "Vietnam"),
    ("antiguaandbarbuda", "Antigua and Barbuda"),
    ("ao", "Angola"),
    ("aorōkin m̧ajeļ", "Marshall Islands"),
    ("aorōkinm̧ajeļ", "Marshall Islands"),
    ("aotearoa", "New Zealand"),
    ("aq", "Antarctica"),
    ("ar", "Argentina"),
    ("arab emir ates", "United Arab Emirates"),
    ("arab emirates", "United Arab Emirates"),
    ("arab republic of egypt", "Egypt"),
    ("arabemirates", "United Arab Emirates"),
    ("arabrepublicofegypt", "Egypt"),
    ("argenina", "Argentina"),
    ("argentiha", "Argentina"),
    ("argentine republic", "Argentina"),
    ("argentine", "Argentina"),
    ("argentinerepublic", "Argentina"),
    ("argentinia", "Argentina"),
    ("argentna", "Argentina"),
    ("arima", "Armenia"),
    ("arminia", "Armenia"),
    ("as", "American Samoa"),
    ("ascension island", "Ascension"),
    ("ascensionisland", "Ascension"),
    ("assudan", "Sudan"),
    ("at", "Austria"),
    ("au", "Australia"),
    ("ausralia", "Australia"),
    ("austalia", "Australia"),
    ("austraila", "Australia"),
    ("austrailia", "Australia"),
    ("australa", "Australia"),
    ("australla", "Australia"),
    ("austrilia", "Australia"),
    ("austrlia", "Australia"),
    ("autralia", "Australia"),
    ("avstralia", "Australia"),
    ("avstria", "Australia"),
    ("aw", "Aruba"),
    ("ax", "Åland Islands"),
    ("ayiti", "Haiti"),
    ("az", "Azerbaijan"),
    ("azebaijan", "Azerbaijan"),
    ("azeraijan", "Azerbaijan"),
    ("azerbaijani republic", "Azerbaijan"),
    ("azerbaijanirepublic", "Azerbaijan"),
    ("azerbaijann", "Azerbaijan"),
    ("azerbaisan", "Azerbaijan"),
    ("azerbaizan", "Azerbaijan"),
    ("azerbajan", "Azerbaijan"),
    ("azerbajdzhan republic", "Azerbaijan"),
    ("azerbajdzhan", "Azerbaijan"),
    ("azerbajdzhanrepublic", "Azerbaijan"),
    ("azerbaycan", "Azerbaijan"),
    ("azerbayjan", "Azerbaijan"),
    ("azerbeyjan", "Azerbaijan"),
    ("azerbpijan", "Azerbaijan"),
    ("azərbaycan", "Azerbaijan"),
    ("aşşūmāl", "Somalia"),
    ("ba", "Bosnia and Herzegovina"),
    ("bailiwick of guernsey", "United Kingdom"),
    ("bailiwick of jersey", "United Kingdom"),
    ("bailiwickofguernsey", "United Kingdom"),
    ("bailiwickofjersey", "United Kingdom"),
    ("bakerisland", "Baker Island"),
    ("bangla desh", "Bangladesh"),
    ("basutoland", "Lesotho"),
    ("bat", "British Antarctic Territory"),
    ("bb", "Barbados"),
    ("bd", "Bangladesh"),
    ("be", "Belgium"),
    ("belau", "Palau"),
    ("belgie", "Belgium"),
    ("belgien", "Belgium"),
    ("belgique", "Belgium"),
    ("belgië", "Belgium"),
    ("belguim", "Belgium"),
    ("bermudas", "Bermuda"),
    ("bf", "Burkina Faso"),
    ("bg", "Bulgaria"),
    ("bh", "Bahrain"),
    ("bharat", "India"),
    ("bharôt", "India"),
    ("bharôtô", "India"),
    ("bhārat", "India"),
    ("bhārata", "India"),
    ("bhāratadēsam", "India"),
    ("bhāratam", "India"),
    ("bi", "Burundi"),
    ("bielaruś", "Belarus"),
    ("bih", "Bosnia and Herzegovina"),
    ("bj", "Benin"),
    ("bl", "Saint Barthélemy"),
    ("bm", "Bermuda"),
    ("bn", "Brunei"),
    ("bo", "Bolivia"),
    ("bolivarian republic of venezuela", "Venezuela"),
    ("bolivarianrepublicofvenezuela", "Venezuela"),
    ("bosna i hercegovina", "Bosnia and Herzegovina"),
    ("bosnaihercegovina", "Bosnia and Herzegovina"),
    ("bosniaandherzegovina", "Bosnia and Herzegovina"),
    ("bosniaherzegovina", "Bosnia and Herzegovina"),
    ("bouvetisland", "Bouvet Island"),
    ("bqbo", "Bonaire"),
    ("bqsa", "Saba"),
    ("bqse", "Sint Eustatius"),
    ("br", "Brazil"),
    ("brasil", "Brazil"),
    ("brazzaville", "Congo"),
    ("british guiana", "Guyana"),
    ("british honduras", "Belize"),
    ("britishantarcticterritory", "British Antarctic Territory"),
    ("britishguiana", "Guyana"),
    ("britishhonduras", "Belize"),
    ("britishindianoceanterritory", "British Indian Ocean Territory"),
    ("britishvirginislands", "British Virgin Islands"),
    ("brunei darussalam", "Brunei"),
    ("bruneidarussalam", "Brunei"),
    ("bs", "The Bahamas"),
    ("bt", "Bhutan"),
    ("bugaria", "Bulgaria"),
    ("bukchosŏn", "North Korea"),
    ("bulagar", "Bulgaria"),
    ("bulgariya", "Bulgaria"),
    ("buliwya", "Bolivia"),
    ("bundesrepublik", "Germany"),
    ("burkina fasoupper", "Burkina Faso"),
    ("burkinafaso", "Burkina Faso"),
    ("burkinafasoupper", "Burkina Faso"),
    ("bv", "Bouvet Island"),
    ("bvi", "British Virgin Islands"),
    ("bw", "Botswana"),
    ("by", "Belarus"),
    ("byelarus", "Belarus"),
    ("byelorussia", "Belarus"),
    ("bz", "Belize"),
    ("bārata", "India"),
    ("bălgarija", "Bulgaria"),
    ("ca", "Canada"),
    ("cabo verde", "Cape Verde"),
    ("cabo", "Cape Verde"),
    ("caboverde", "Cape Verde"),
    ("cameroun", "Cameroon"),
    ("canadaigua", "Canada"),
    ("candada", "Canada"),
    ("capeverde", "Cape Verde"),
    ("car", "Central African Republic"),
    ("cathay", "China"),
    ("caymanislands", "Cayman Islands"),
    ("cc", "Cocos (Keeling) Islands"),
    ("cd", "Congo (Democratic Republic)"),
    ("central africa", "Central African Republic"),
    ("centralafrica", "Central African Republic"),
    ("centralafricanrepublic", "Central African Republic"),
    ("ceska", "Czechia"),
    ("ceylon", "Sri Lanka"),
    ("cf", "Central African Republic"),
    ("cg", "Congo"),
    ("ch", "Switzerland"),
    ("chinese taipei", "Taiwan"),
    ("chinesetaipei", "Taiwan"),
    ("christmasisland", "Christmas Island"),
    ("ci", "Ivory Coast"),
    ("citta del vaticano", "Vatican City"),
    ("cittadelvaticano", "Vatican City"),
    ("ck", "Cook Islands"),
    ("cl", "Chile"),
    ("cm", "Cameroon"),
    ("cn", "China"),
    ("co", "Colombia"),
    ("coasta rica", "Costa Rica"),
    ("coastarica", "Costa Rica"),
    ("cocos(keeling)islands", "Cocos (Keeling) Islands"),
    ("collectivity of saint martin", "Saint-Martin (French part)"),
    ("collectivityofsaintmartin", "Saint-Martin (French part)"),
    ("commonwealth of australia", "Australia"),
    ("commonwealth of bahamas", "The Bahamas"),
    ("commonwealth of dominica", "Dominica"),
    ("commonwealth of puerto rico", "Puerto Rico"),
    ("commonwealth of the northern mariana islands", "Northern Mariana Islands"),
    ("commonwealthofaustralia", "Australia"),
    ("commonwealthofbahamas", "The Bahamas"),
    ("commonwealthofdominica", "Dominica"),
    ("commonwealthofpuertorico", "Puerto Rico"),
    ("commonwealthofthenorthernmarianaislands", "Northern Mariana Islands"),
    ("comores", "Comoros"),
    ("congo(democraticrepublic)", "Congo (Democratic Republic)"),
    ("congobrazzaville", "Congo (Democratic Republic)"),
    ("cookislands", "Cook Islands"),
    ("cooperative republic of guyana", "Guyana"),
    ("cooperativerepublicofguyana", "Guyana"),
    ("costa rico", "Costa Rica"),
    ("costarica", "Costa Rica"),
    ("costarico", "Costa Rica"),
    ("cote divoire", "Ivory Coast"),
    ("cotedivoire", "Ivory Coast"),
    ("country of curaçao", "Curaçao"),
    ("countryofcuraçao", "Curaçao"),
    ("cr", "Costa Rica"),
    ("crna gora", "Montenegro"),
    ("crnagora", "Montenegro"),
    ("cs", "Czechia"),
    ("cu", "Cuba"),
    ("curacao", "Curaçao"),
    ("cv", "Cape Verde"),
    ("cw", "Curaçao"),
    ("cx", "Christmas Island"),
    ("cy", "Cyprus"),
    ("cz", "Czechia"),
    ("czech republic", "Czechia"),
    ("czechoslav", "Czechia"),
    ("czechoslovak republic", "Czechia"),
    ("czechoslovakrepublic", "Czechia"),
    ("czechrepublic", "Czechia"),
    ("dahomey", "Benin"),
    ("danmark", "Denmark"),
    ("dawlat ulkuwayt", "Kuwait"),
    ("dawlatulkuwayt", "Kuwait"),
    ("dd", "Germany"),
    ("de", "Germany"),
    ("democratic republic of sao tome and principe", "Sao Tome and Principe"),
    ("democratic republic of the congo", "Congo (Democratic Republic)"),
    ("democratic republic of timorlestetimor", "East Timor"),
    ("democratic socialist republic of sri lanka", "Sri Lanka"),
    ("democraticrepublicofsaotomeandprincipe", "Sao Tome and Principe"),
    ("democraticrepublicofthecongo", "Congo (Democratic Republic)"),
    ("democraticrepublicoftimorlestetimor", "East Timor"),
    ("democraticsocialistrepublicofsrilanka", "Sri Lanka"),
    ("deutschland", "Germany"),
    ("dhivehi raajje", "Maldives"),
    ("dhivehiraajje", "Maldives"),
    ("dj", "Djibouti"),
    ("dk", "Denmark"),
    ("dm", "Dominica"),
    ("do", "Dominican Republic"),
    ("dominicanrepublic", "Dominican Republic"),
    ("dominique", "Dominica"),
    ("dprk", "North Korea"),
    ("druk yul", "Bhutan"),
    ("drukyul", "Bhutan"),
    ("ducie and oeno islands", "Pitcairn, Henderson, Ducie and Oeno Islands"),
    ("ducieandoenoislands", "Pitcairn, Henderson, Ducie and Oeno Islands"),
    ("dutch east indies", "Indonesia"),
    ("dutcheastindies", "Indonesia"),
    ("dz", "Algeria"),
    ("dzayer", "Algeria"),
    ("e civitate vaticana", "Vatican City"),
    ("east pakistan", "Bangladesh"),
    ("eastern samoa", "American Samoa"),
    ("easternsamoa", "American Samoa"),
    ("eastgermany", "Germany"),
    ("eastpakistan", "Bangladesh"),
    ("easttimor", "East Timor"),
    ("ec", "Ecuador"),
    ("ecivitatevaticana", "Vatican City"),
    ("ee", "Estonia"),
    ("eesti", "Estonia"),
    ("eg", "Egypt"),
    ("egpyt", "Egypt"),
    ("egyot", "Egypt"),
    ("egyt", "Egypt"),
    ("eh", "Western Sahara"),
    ("eire", "Ireland"),
    ("ellada", "Greece"),
    ("ellan vannin", "United Kingdom"),
    ("ellanvannin", "United Kingdom"),
    ("ellas", "Greece"),
    ("ellice islands", "Tuvalu"),
    ("elliceislands", "Tuvalu"),
    ("elmeɣrib", "Morocco"),
    ("elsalvador", "El Salvador"),
    ("emirate of abu dhabi", "Abu Dhabi"),
    ("emirate of ajman", "Ajman"),
    ("emirate of dubai", "Dubai"),
    ("emirate of fujairah", "Fujairah"),
    ("emirate of ras alkhaimah", "Ras al-Khaimah"),
    ("emirate of sharjah", "Sharjah"),
    ("emirate of umm alquwain", "Umm al-Quwain"),
    ("emirateofabudhabi", "Abu Dhabi"),
    ("emirateofajman", "Ajman"),
    ("emirateofdubai", "Dubai"),
    ("emirateoffujairah", "Fujairah"),
    ("emirateofrasalkhaimah", "Ras al-Khaimah"),
    ("emirateofsharjah", "Sharjah"),
    ("emirateofummalquwain", "Umm al-Quwain"),
    ("equatorialguinea", "Equatorial Guinea"),
    ("er", "Eritrea"),
    ("ertra", "Eritrea"),
    ("es", "Spain"),
    ("esce", "Ceuta"),
    ("esml", "Melilla"),
    ("espainia", "Spain"),
    ("espanha", "Spain"),
    ("espanya", "Spain"),
    ("españa", "Spain"),
    ("estados unidos", "United States"),
    ("estadosunidos", "United States"),
    ("esthonia", "Estonia"),
    ("et", "Ethiopia"),
    ("ethopi", "Ethiopia"),
    ("falklandislands", "Falkland Islands"),
    ("faroeislands", "Faroe Islands"),
    ("faroes", "Faroe Islands"),
    ("federal democratic republic of ethiopia", "Ethiopia"),
    ("federal democratic republic of nepal", "Nepal"),
    ("federal islamic republic of the comoros", "Comoros"),
    ("federal republic of germany", "Germany"),
    ("federal republic of nigeria", "Nigeria"),
    ("federal republic of somalia", "Somalia"),
    ("federal republic of somaliaaiai", "Somalia"),
    ("federaldemocraticrepublicofethiopia", "Ethiopia"),
    ("federaldemocraticrepublicofnepal", "Nepal"),
    ("federalislamicrepublicofthecomoros", "Comoros"),
    ("federalrepublicofgermany", "Germany"),
    ("federalrepublicofnigeria", "Nigeria"),
    ("federalrepublicofsomalia", "Somalia"),
    ("federalrepublicofsomaliaaiai", "Somalia"),
    ("federated states of micronesia", "Micronesia"),
    ("federatedstatesofmicronesia", "Micronesia"),
    ("federation of malaysia", "Malaysia"),
    ("federation of saint christopher and nevis", "St Kitts and Nevis"),
    ("federationofmalaysia", "Malaysia"),
    ("federationofsaintchristopherandnevis", "St Kitts and Nevis"),
    ("federative republic of brazil", "Brazil"),
    ("federativerepublicofbrazil", "Brazil"),
    ("fi", "Finland"),
    ("fj", "Fiji"),
    ("fk", "Falkland Islands"),
    ("fm", "Micronesia"),
    ("fo", "Faroe Islands"),
    ("fr", "France"),
    ("french congo", "Congo"),
    ("french guinea", "Guinea"),
    ("french oceania", "French Polynesia"),
    ("french republic", "France"),
    ("french sudan", "Mali"),
    ("frenchcongo", "Congo"),
    ("frenchguiana", "French Guiana"),
    ("frenchguinea", "Guinea"),
    ("frenchoceania", "French Polynesia"),
    ("frenchpolynesia", "French Polynesia"),
    ("frenchrepublic", "France"),
    ("frenchsouthernterritories", "French Southern Territories"),
    ("frenchsudan", "Mali"),
    ("frg", "Germany"),
    ("friendly islands", "Tonga"),
    ("friendlyislands", "Tonga"),
    ("færøerne", "Faroe Islands"),
    ("føroyar", "Faroe Islands"),
    ("ga", "Gabon"),
    ("gabonese republic", "Gabon"),
    ("gaboneserepublic", "Gabon"),
    ("gabun", "Gabon"),
    ("gabuuti", "Djibouti"),
    ("gd", "Grenada"),
    ("ge", "Georgia"),
    ("genus argentina", "Argentina"),
    ("genusargentina", "Argentina"),
    ("germany democratic republic", "Germany"),
    ("germanydemocraticrepublic", "Germany"),
    ("gf", "French Guiana"),
    ("gg", "United Kingdom"),
    ("gh", "Ghana"),
    ("gi", "Gibraltar"),
    ("gine", "Guinea"),
    ("gl", "Greenland"),
    ("gm", "The Gambia"),
    ("gn", "Guinea"),
    ("gold coast", "Ghana"),
    ("goldcoast", "Ghana"),
    ("gp", "Guadeloupe"),
    ("gq", "Equatorial Guinea"),
    ("gr", "Greece"),
    ("grand duchy of luxembourg", "Luxembourg"),
    ("grandduchyofluxembourg", "Luxembourg"),
    ("gronland", "Greenland"),
    ("grønland", "Greenland"),
    ("gs", "South Georgia and South Sandwich Islands"),
    ("gt", "Guatemala"),
    ("gu", "Guam"),
    ("guinea ecuatorial", "Equatorial Guinea"),
    ("guineaecuatorial", "Equatorial Guinea"),
    ("guinée", "Guinea"),
    ("guyane", "French Guiana"),
    ("guåhån", "Guam"),
    ("gw", "Guinea-Bissau"),
    ("gy", "Guyana"),
    ("hanguk", "South Korea"),
    ("hashemite kingdom of jordan", "Jordan"),
    ("hashemitekingdomofjordan", "Jordan"),
    ("hayastan", "Armenia"),
    ("hayastán", "Armenia"),
    ("haïti", "Haiti"),
    ("heardislandandmcdonaldislands", "Heard Island and McDonald Islands"),
    ("hellas", "Greece"),
    ("hellenic republic", "Greece"),
    ("hellenicrepublic", "Greece"),
    ("henderson", "Pitcairn, Henderson, Ducie and Oeno Islands"),
    ("heung gong", "Hong Kong"),
    ("heunggong", "Hong Kong"),
    ("hindustan", "India"),
    ("hk", "Hong Kong"),
    ("hm", "Heard Island and McDonald Islands"),
    ("hn", "Honduras"),
    ("holland", "Netherlands"),
    ("holy see", "Vatican City"),
    ("holysee", "Vatican City"),
    ("hong kong special administrative region", "Hong Kong"),
    ("hongkong", "Hong Kong"),
    ("hongkongspecialadministrativeregion", "Hong Kong"),
    ("howlandisland", "Howland Island"),
    ("hr", "Croatia"),
    ("hrvatska", "Croatia"),
    ("ht", "Haiti"),
    ("hu", "Hungary"),
    ("id", "Indonesia"),
    ("ie", "Ireland"),
    ("il", "Israel"),
    ("ilikwet", "Kuwait"),
    ("im", "United Kingdom"),
    ("in", "India"),
    ("independent state of papua new guinea", "Papua New Guinea"),
    ("independent state of samoa", "Samoa"),
    ("independentstateofpapuanewguinea", "Papua New Guinea"),
    ("independentstateofsamoa", "Samoa"),
    ("iningizimu afrika", "South Africa"),
    ("iningizimuafrika", "South Africa"),
    ("io", "British Indian Ocean Territory"),
    ("iot", "British Indian Ocean Territory"),
    ("iq", "Iraq"),
    ("ir", "Iran"),
    ("irak", "Iraq"),
    ("irelend", "Ireland"),
    ("irish republic", "Ireland"),
    ("irishrepublic", "Ireland"),
    ("iritriya", "Eritrea"),
    ("is", "Iceland"),
    ("isewula afrika", "South Africa"),
    ("isewulaafrika", "South Africa"),
    ("islamic republic of afghanistan", "Afghanistan"),
    ("islamic republic of gambia", "The Gambia"),
    ("islamic republic of iran", "Iran"),
    ("islamic republic of mauritania", "Mauritania"),
    ("islamic republic of pakistan", "Pakistan"),
    ("islamicrepublicofafghanistan", "Afghanistan"),
    ("islamicrepublicofgambia", "The Gambia"),
    ("islamicrepublicofiran", "Iran"),
    ("islamicrepublicofmauritania", "Mauritania"),
    ("islamicrepublicofpakistan", "Pakistan"),
    ("island of guernsey", "United Kingdom"),
    ("island of jersey", "United Kingdom"),
    ("island", "Iceland"),
    ("islandofguernsey", "United Kingdom"),
    ("islandofjersey", "United Kingdom"),
    ("isleofman", "United Kingdom"),
    ("israʼiyl", "Israel"),
    ("isreal", "Israel"),
    ("it", "Italy"),
    ("italia", "Italy"),
    ("italian republic", "Italy"),
    ("italianrepublic", "Italy"),
    ("itlay", "Italy"),
    ("ivorycoast", "Ivory Coast"),
    ("jabuuti", "Djibouti"),
    ("jamaca", "Jamaica"),
    ("jamacia", "Jamaica"),
    ("jamahiriya", "Libya"),
    ("jarvisisland", "Jarvis Island"),
    ("je", "United Kingdom"),
    ("jm", "Jamaica"),
    ("jo", "Jordan"),
    ("johnstonatoll", "Johnston Atoll"),
    ("jp", "Japan"),
    ("juzur alqamar", "Comoros"),
    ("juzuralqamar", "Comoros"),
    ("jèrri", "Tuvalu"),
    ("jībūtī", "Djibouti"),
    ("kalaallit nunaat", "Greenland"),
    ("kalaallitnunaat", "Greenland"),
    ("kampuchea", "Cambodia"),
    ("kangwane", "Eswatini"),
    ("katar", "Qatar"),
    ("kazakh", "Kazakhstan"),
    ("kazakhstán", "Kazakhstan"),
    ("kazakstan", "Kazakhstan"),
    ("ke", "Kenya"),
    ("kg", "Kyrgyzstan"),
    ("kh", "Cambodia"),
    ("ki", "Kiribati"),
    ("kingdom of bahrain", "Bahrain"),
    ("kingdom of belgium", "Belgium"),
    ("kingdom of bhutan", "Bhutan"),
    ("kingdom of cambodia", "Cambodia"),
    ("kingdom of denmark", "Denmark"),
    ("kingdom of eswatini", "Eswatini"),
    ("kingdom of lesotho", "Lesotho"),
    ("kingdom of moroccoalmagrib", "Morocco"),
    ("kingdom of norway", "Norway"),
    ("kingdom of saudi arabia", "Saudi Arabia"),
    ("kingdom of spain", "Spain"),
    ("kingdom of swaziland", "Eswatini"),
    ("kingdom of sweden", "Sweden"),
    ("kingdom of thailand", "Thailand"),
    ("kingdom of the netherlands", "Netherlands"),
    ("kingdom of tonga", "Tonga"),
    ("kingdomofbahrain", "Bahrain"),
    ("kingdomofbelgium", "Belgium"),
    ("kingdomofbhutan", "Bhutan"),
    ("kingdomofcambodia", "Cambodia"),
    ("kingdomofdenmark", "Denmark"),
    ("kingdomofeswatini", "Eswatini"),
    ("kingdomoflesotho", "Lesotho"),
    ("kingdomofmoroccoalmagrib", "Morocco"),
    ("kingdomofnorway", "Norway"),
    ("kingdomofsaudiarabia", "Saudi Arabia"),
    ("kingdomofspain", "Spain"),
    ("kingdomofswaziland", "Eswatini"),
    ("kingdomofsweden", "Sweden"),
    ("kingdomofthailand", "Thailand"),
    ("kingdomofthenetherlands", "Netherlands"),
    ("kingdomoftonga", "Tonga"),
    ("kingmanreef", "Kingman Reef"),
    ("kirghizia", "Kyrgyzstan"),
    ("kirghizstan", "Kyrgyzstan"),
    ("kirgiz", "Kyrgyzstan"),
    ("kirgizia", "Kyrgyzstan"),
    ("kirgizija", "Kyrgyzstan"),
    ("kirgizstan", "Kyrgyzstan"),
    ("km", "Comoros"),
    ("kn", "St Kitts and Nevis"),
    ("komori", "Comoros"),
    ("kosova", "Kosovo"),
    ("koweit", "Kuwait"),
    ("kp", "North Korea"),
    ("kr", "South Korea"),
    ("kw", "Kuwait"),
    ("ky", "Cayman Islands"),
    ("kypros", "Cyprus"),
    ("kyrgyz republic", "Kyrgyzstan"),
    ("kyrgyz republickirghiz", "Kyrgyzstan"),
    ("kyrgyzrepublic", "Kyrgyzstan"),
    ("kyrgyzrepublickirghiz", "Kyrgyzstan"),
    ("kz", "Kazakhstan"),
    ("kòrsou", "Curaçao"),
    ("ködörösêse tî bêafrîka", "Central African Republic"),
    ("ködörösêsetîbêafrîka", "Central African Republic"),
    ("kýpros", "Cyprus"),
    ("kıbrıs", "Cyprus"),
    ("la", "Laos"),
    ("lao", "Laos"),
    ("las malvinas", "Falkland Islands"),
    ("lasmalvinas", "Falkland Islands"),
    ("latvija", "Latvia"),
    ("latvijaz", "Latvia"),
    ("lb", "Lebanon"),
    ("lc", "St Lucia"),
    ("lebanese republic", "Lebanon"),
    ("lebaneserepublic", "Lebanon"),
    ("li", "Liechtenstein"),
    ("lietuva", "Lithuania"),
    ("lk", "Sri Lanka"),
    ("lr", "Liberia"),
    ("ls", "Lesotho"),
    ("lt", "Lithuania"),
    ("lu", "Luxembourg"),
    ("lubnān", "Lebanon"),
    ("luxemborg", "Luxembourg"),
    ("luxemburg", "Luxembourg"),
    ("lv", "Latvia"),
    ("ly", "Libya"),
    ("lëtzebuerg", "Luxembourg"),
    ("lībiyā", "Libya"),
    ("ma", "Morocco"),
    ("macao special administrative region", "Macao"),
    ("macaospecialadministrativeregion", "Macao"),
    ("macedon", "North Macedonia"),
    ("madagasikara", "Madagascar"),
    ("magyarorszag", "Hungary"),
    ("magyarország", "Hungary"),
    ("mainland china", "China"),
    ("mainlandchina", "China"),
    ("makedonija", "North Macedonia"),
    ("malagasy republic", "Madagascar"),
    ("malagasyrepublic", "Madagascar"),
    ("malyasi", "Malaysia"),
    ("malēṣiyā", "Malaysia"),
    ("maroc", "Morocco"),
    ("marruecos", "Morocco"),
    ("marshallislands", "Marshall Islands"),
    ("masr", "Egypt"),
    ("maurice", "Mauritius"),
    ("mauritanie", "Mauritania"),
    ("mc", "Monaco"),
    ("md", "Moldova"),
    ("me", "Montenegro"),
    ("mexcio", "Mexico"),
    ("mexicanos", "Mexico"),
    ("mexixo", "Mexico"),
    ("mf", "Saint-Martin (French part)"),
    ("mg", "Madagascar"),
    ("mh", "Marshall Islands"),
    ("midwayislands", "Midway Islands"),
    ("misr", "Egypt"),
    ("mk", "North Macedonia"),
    ("ml", "Mali"),
    ("mm", "Myanmar (Burma)"),
    ("mn", "Mongolia"),
    ("mo", "Macao"),
    ("mocambique", "Mozambique"),
    ("moldavia", "Moldova"),
    ("mongol uls", "Mongolia"),
    ("mongoluls", "Mongolia"),
    ("mongγol ulus", "Mongolia"),
    ("mongγolulus", "Mongolia"),
    ("moris", "Mauritius"),
    ("moçambique", "Mozambique"),
    ("mp", "Northern Mariana Islands"),
    ("mq", "Martinique"),
    ("mr", "Mauritania"),
    ("ms", "Montserrat"),
    ("mt", "Malta"),
    ("mu", "Mauritius"),
    ("mueang thai", "Thailand"),
    ("mueangthai", "Thailand"),
    ("muritan", "Mauritania"),
    ("muritaniya", "Mauritania"),
    ("muscat and oman", "Oman"),
    ("muscatandoman", "Oman"),
    ("mv", "Maldives"),
    ("mw", "Malawi"),
    ("mx", "Mexico"),
    ("my", "Malaysia"),
    ("myanma", "Myanmar (Burma)"),
    ("myanmar(burma)", "Myanmar (Burma)"),
    ("mz", "Mozambique"),
    ("méxico", "Mexico"),
    ("mēxihco", "Mexico"),
    ("mūrītānyā", "Mauritania"),
    ("mǎláixīyà", "Malaysia"),
    ("na", "Namibia"),
    ("namhan", "South Korea"),
    ("namibië", "Namibia"),
    ("naoero", "Nauru"),
    ("navassaisland", "Navassa Island"),
    ("naíjíríà", "Nigeria"),
    ("nc", "New Caledonia"),
    ("ne", "Niger"),
    ("nederland", "Netherlands"),
    ("nederlân", "Netherlands"),
    ("nepāl", "Nepal"),
    ("new hebrides", "Vanuatu"),
    ("newcaledonia", "New Caledonia"),
    ("newhebrides", "Vanuatu"),
    ("newzealand", "New Zealand"),
    ("nf", "Norfolk Island"),
    ("ng", "Nigeria"),
    ("ngwane", "Eswatini"),
    ("nihon", "Japan"),
    ("nijar", "Niger"),
    ("nijeriya", "Nigeria"),
    ("nippon", "Japan"),
    ("niuē", "Niue"),
    ("nl", "Netherlands"),
    ("no", "Norway"),
    ("noreg", "Norway"),
    ("norfolkisland", "Norfolk Island"),
    ("norge", "Norway"),
    ("northern marianas", "Northern Mariana Islands"),
    ("northern rhodesia", "Zambia"),
    ("northernmarianaislands", "Northern Mariana Islands"),
    ("northernmarianas", "Northern Mariana Islands"),
    ("northernrhodesia", "Zambia"),
    ("northkorea", "North Korea"),
    ("northmacedonia", "North Macedonia"),
    ("nouvellecalédonie", "New Caledonia"),
    ("np", "Nepal"),
    ("nr", "Nauru"),
    ("nu", "Niue"),
    ("nyasaland", "Malawi"),
    ("nz", "New Zealand"),
    ("occupiedpalestinianterritories", "Occupied Palestinian Territories"),
    ("oesterreich", "Austria"),
    ("om", "Oman"),
    ("oriental republic of uruguay", "Uruguay"),
    ("orientalrepublicofuruguay", "Uruguay"),
    ("osterreich", "Austria"),
    ("outer mongolia", "Mongolia"),
    ("outermongolia", "Mongolia"),
    ("o‘zbekiston", "Uzbekistan"),
    ("o’zbekstan", "Uzbekistan"),
    ("pa", "Panama"),
    ("palmyraatoll", "Palmyra Atoll"),
    ("panamá", "Panama"),
    ("papua niugini", "Papua New Guinea"),
    ("papuanewguinea", "Papua New Guinea"),
    ("papuaniugini", "Papua New Guinea"),
    ("paraguái", "Paraguay"),
    ("pe", "Peru"),
    ("pelew", "Palau"),
    ("peoples republic", "China"),
    ("peoplesrepublic", "China"),
    ("persia", "Iran"),
    ("perú", "Peru"),
    ("pf", "French Polynesia"),
    ("pg", "Papua New Guinea"),
    ("ph", "Philippines"),
    ("philippine islands", "Philippines"),
    ("philippineislands", "Philippines"),
    ("phillippine", "Philippines"),
    ("pilipinas", "Philippines"),
    ("pinas", "Philippines"),
    ("piruw", "Peru"),
    ("pitcairn", "Pitcairn, Henderson, Ducie and Oeno Islands"),
    (
        "pitcairn,henderson,ducieandoenoislands",
        "Pitcairn, Henderson, Ducie and Oeno Islands",
    ),
    ("pk", "Pakistan"),
    ("pl", "Poland"),
    ("plurinational state of bolivia", "Bolivia"),
    ("plurinationalstateofbolivia", "Bolivia"),
    ("pm", "Saint Pierre and Miquelon"),
    ("pn", "Pitcairn, Henderson, Ducie and Oeno Islands"),
    ("png", "Papua New Guinea"),
    ("polska", "Poland"),
    ("polynésie française", "French Polynesia"),
    ("polynésiefrançaise", "French Polynesia"),
    ("porto rico", "Puerto Rico"),
    ("portorico", "Puerto Rico"),
    ("portuguesa", "Portugal"),
    ("portuguese guinea", "Guinea-Bissau"),
    ("portuguese republic", "Portugal"),
    ("portugueseguinea", "Guinea-Bissau"),
    ("portugueserepublic", "Portugal"),
    ("pr", "Puerto Rico"),
    ("prathet thai", "Thailand"),
    ("prathetthai", "Thailand"),
    ("prc", "China"),
    ("principality of andorra", "Andorra"),
    ("principality of liechtenstein", "Liechtenstein"),
    ("principality of monaco", "Monaco"),
    ("principalityofandorra", "Andorra"),
    ("principalityofliechtenstein", "Liechtenstein"),
    ("principalityofmonaco", "Monaco"),
    ("prk", "North Korea"),
    ("ps", "Occupied Palestinian Territories"),
    ("pt", "Portugal"),
    ("puarto rico", "Puerto Rico"),
    ("puartorico", "Puerto Rico"),
    ("puertorico", "Puerto Rico"),
    ("pw", "Palau"),
    ("py", "Paraguay"),
    ("qa", "Qatar"),
    ("qazaqstan", "Kazakhstan"),
    ("rasalkhaimah", "Ras al-Khaimah"),
    ("rastafari", "Jamaica"),
    ("rastas", "Jamaica"),
    ("ratchaanachak thai", "Thailand"),
    ("ratchaanachakthai", "Thailand"),
    ("re", "Réunion"),
    ("rep of ireland", "Ireland"),
    ("repubblica", "San Marino"),
    ("repubilika ya kongo", "Congo (Democratic Republic)"),
    ("repubilikayakongo", "Congo (Democratic Republic)"),
    ("republic of albania", "Albania"),
    ("republic of angola", "Angola"),
    ("republic of armenia", "Armenia"),
    ("republic of austria", "Austria"),
    ("republic of azerbaijan", "Azerbaijan"),
    ("republic of belarusbelorussia", "Belarus"),
    ("republic of benin", "Benin"),
    ("republic of bosnia and herzegovina", "Bosnia and Herzegovina"),
    ("republic of botswana", "Botswana"),
    ("republic of bulgaria", "Bulgaria"),
    ("republic of burundi", "Burundi"),
    ("republic of cabo verde", "Cape Verde"),
    ("republic of cameroon", "Cameroon"),
    ("republic of chad", "Chad"),
    ("republic of chile", "Chile"),
    ("republic of colombia", "Colombia"),
    ("republic of costa rica", "Costa Rica"),
    ("republic of croatia", "Croatia"),
    ("republic of cuba", "Cuba"),
    ("republic of cyprus", "Cyprus"),
    ("republic of djibouti", "Djibouti"),
    ("republic of ecuador", "Ecuador"),
    ("republic of el salvador", "El Salvador"),
    ("republic of equatorial guinea", "Equatorial Guinea"),
    ("republic of estonia", "Estonia"),
    ("republic of fiji", "Fiji"),
    ("republic of finland", "Finland"),
    ("republic of ghana", "Ghana"),
    ("republic of guatemala", "Guatemala"),
    ("republic of guinea", "Guinea"),
    ("republic of guineabissau", "Guinea-Bissau"),
    ("republic of haiti", "Haiti"),
    ("republic of honduras", "Honduras"),
    ("republic of iceland", "Iceland"),
    ("republic of india", "India"),
    ("republic of indonesia", "Indonesia"),
    ("republic of iraq", "Iraq"),
    ("republic of ireland", "Ireland"),
    ("republic of kazakhstankazak", "Kazakhstan"),
    ("republic of kenya", "Kenya"),
    ("republic of kiribati", "Kiribati"),
    ("republic of korea", "South Korea"),
    ("republic of kosovo", "Kosovo"),
    ("republic of latvia", "Latvia"),
    ("republic of liberia", "Liberia"),
    ("republic of lithuanialietuva", "Lithuania"),
    ("republic of macedonia", "North Macedonia"),
    ("republic of madagascar", "Madagascar"),
    ("republic of malawi", "Malawi"),
    ("republic of maldives", "Maldives"),
    ("republic of mali", "Mali"),
    ("republic of malta", "Malta"),
    ("republic of mauritius", "Mauritius"),
    ("republic of moldova", "Moldova"),
    ("republic of mozambique", "Mozambique"),
    ("republic of namibia", "Namibia"),
    ("republic of nauru", "Nauru"),
    ("republic of nicaragua", "Nicaragua"),
    ("republic of niger", "Niger"),
    ("republic of palau", "Palau"),
    ("republic of panama", "Panama"),
    ("republic of paraguay", "Paraguay"),
    ("republic of peru", "Peru"),
    ("republic of poland", "Poland"),
    ("republic of rwandaruanda", "Rwanda"),
    ("republic of san marino", "San Marino"),
    ("republic of senegal", "Senegal"),
    ("republic of serbia", "Serbia"),
    ("republic of seychelles", "Seychelles"),
    ("republic of sierra leone", "Sierra Leone"),
    ("republic of singapore", "Singapore"),
    ("republic of slovenia", "Slovenia"),
    ("republic of south africa", "South Africa"),
    ("republic of south sudan", "South Sudan"),
    ("republic of suriname", "Suriname"),
    ("republic of tajikistantadjik", "Tajikistan"),
    ("republic of the congo", "Congo"),
    ("republic of the marshall islands", "Marshall Islands"),
    ("republic of the philippines", "Philippines"),
    ("republic of the sudan", "Sudan"),
    ("republic of the union of myanmar", "Myanmar (Burma)"),
    ("republic of trinidad and tobago", "Trinidad and Tobago"),
    ("republic of turkey", "Turkey"),
    ("republic of uganda", "Uganda"),
    ("republic of uzbekistan", "Uzbekistan"),
    ("republic of vanuatu", "Vanuatu"),
    ("republic of yemen", "Yemen"),
    ("republic of zambia", "Zambia"),
    ("republic of zimbabwe", "Zimbabwe"),
    ("republicofalbania", "Albania"),
    ("republicofangola", "Angola"),
    ("republicofarmenia", "Armenia"),
    ("republicofaustria", "Austria"),
    ("republicofazerbaijan", "Azerbaijan"),
    ("republicofbelarusbelorussia", "Belarus"),
    ("republicofbenin", "Benin"),
    ("republicofbosniaandherzegovina", "Bosnia and Herzegovina"),
    ("republicofbotswana", "Botswana"),
    ("republicofbulgaria", "Bulgaria"),
    ("republicofburundi", "Burundi"),
    ("republicofcaboverde", "Cape Verde"),
    ("republicofcameroon", "Cameroon"),
    ("republicofchad", "Chad"),
    ("republicofchile", "Chile"),
    ("republicofcolombia", "Colombia"),
    ("republicofcostarica", "Costa Rica"),
    ("republicofcroatia", "Croatia"),
    ("republicofcuba", "Cuba"),
    ("republicofcyprus", "Cyprus"),
    ("republicofdjibouti", "Djibouti"),
    ("republicofecuador", "Ecuador"),
    ("republicofelsalvador", "El Salvador"),
    ("republicofequatorialguinea", "Equatorial Guinea"),
    ("republicofestonia", "Estonia"),
    ("republicoffiji", "Fiji"),
    ("republicoffinland", "Finland"),
    ("republicofghana", "Ghana"),
    ("republicofguatemala", "Guatemala"),
    ("republicofguinea", "Guinea"),
    ("republicofguineabissau", "Guinea-Bissau"),
    ("republicofhaiti", "Haiti"),
    ("republicofhonduras", "Honduras"),
    ("republicoficeland", "Iceland"),
    ("republicofindia", "India"),
    ("republicofindonesia", "Indonesia"),
    ("republicofiraq", "Iraq"),
    ("republicofireland", "Ireland"),
    ("republicofkazakhstankazak", "Kazakhstan"),
    ("republicofkenya", "Kenya"),
    ("republicofkiribati", "Kiribati"),
    ("republicofkorea", "South Korea"),
    ("republicofkosovo", "Kosovo"),
    ("republicoflatvia", "Latvia"),
    ("republicofliberia", "Liberia"),
    ("republicoflithuanialietuva", "Lithuania"),
    ("republicofmacedonia", "North Macedonia"),
    ("republicofmadagascar", "Madagascar"),
    ("republicofmalawi", "Malawi"),
    ("republicofmaldives", "Maldives"),
    ("republicofmali", "Mali"),
    ("republicofmalta", "Malta"),
    ("republicofmauritius", "Mauritius"),
    ("republicofmoldova", "Moldova"),
    ("republicofmozambique", "Mozambique"),
    ("republicofnamibia", "Namibia"),
    ("republicofnauru", "Nauru"),
    ("republicofnicaragua", "Nicaragua"),
    ("republicofniger", "Niger"),
    ("republicofpalau", "Palau"),
    ("republicofpanama", "Panama"),
    ("republicofparaguay", "Paraguay"),
    ("republicofperu", "Peru"),
    ("republicofpoland", "Poland"),
    ("republicofrwandaruanda", "Rwanda"),
    ("republicofsanmarino", "San Marino"),
    ("republicofsenegal", "Senegal"),
    ("republicofserbia", "Serbia"),
    ("republicofseychelles", "Seychelles"),
    ("republicofsierraleone", "Sierra Leone"),
    ("republicofsingapore", "Singapore"),
    ("republicofslovenia", "Slovenia"),
    ("republicofsouthafrica", "South Africa"),
    ("republicofsouthsudan", "South Sudan"),
    ("republicofsuriname", "Suriname"),
    ("republicoftajikistantadjik", "Tajikistan"),
    ("republicofthecongo", "Congo"),
    ("republicofthemarshallislands", "Marshall Islands"),
    ("republicofthephilippines", "Philippines"),
    ("republicofthesudan", "Sudan"),
    ("republicoftheunionofmyanmar", "Myanmar (Burma)"),
    ("republicoftrinidadandtobago", "Trinidad and Tobago"),
    ("republicofturkey", "Turkey"),
    ("republicofuganda", "Uganda"),
    ("republicofuzbekistan", "Uzbekistan"),
    ("republicofvanuatu", "Vanuatu"),
    ("republicofyemen", "Yemen"),
    ("republicofzambia", "Zambia"),
    ("republicofzimbabwe", "Zimbabwe"),
    ("república dominicana", "Dominican Republic"),
    ("república oriental del uruguay", "Uruguay"),
    ("repúblicadominicana", "Dominican Republic"),
    ("repúblicaorientaldeluruguay", "Uruguay"),
    ("reunion", "Réunion"),
    ("rgypt", "Egypt"),
    ("rhodesia", "Zimbabwe"),
    ("ro", "Romania"),
    ("roi", "Ireland"),
    ("românia", "Romania"),
    ("rossiya", "Russia"),
    ("rossiâ", "Russia"),
    ("roumania", "Romania"),
    ("rs", "Serbia"),
    ("rsa", "South Africa"),
    ("rsm", "San Marino"),
    ("ru", "Russia"),
    ("rumania", "Romania"),
    ("russian federation", "Russia"),
    ("russianfederation", "Russia"),
    ("rw", "Rwanda"),
    ("rwandese republic", "Rwanda"),
    ("rwandeserepublic", "Rwanda"),
    ("république centrafricaine", "Central African Republic"),
    ("république du congo", "Congo"),
    ("république démocratique du congo", "Congo (Democratic Republic)"),
    ("république française", "France"),
    ("république gabonaise", "Gabon"),
    ("républiquecentrafricaine", "Central African Republic"),
    ("républiqueducongo", "Congo"),
    ("républiquedémocratiqueducongo", "Congo (Democratic Republic)"),
    ("républiquefrançaise", "France"),
    ("républiquegabonaise", "Gabon"),
    ("sa", "Saudi Arabia"),
    ("saint lucia", "St Lucia"),
    ("saint vincent and the grenadines", "St Vincent"),
    ("saintbarthélemy", "Saint Barthélemy"),
    ("sainthelena", "Saint Helena"),
    ("saintlucia", "St Lucia"),
    ("saintmartin(frenchpart)", "Saint-Martin (French part)"),
    ("saintpierre et miquelon", "Saint Pierre and Miquelon"),
    ("saintpierreandmiquelon", "Saint Pierre and Miquelon"),
    ("saintpierreetmiquelon", "Saint Pierre and Miquelon"),
    ("saintvincentandthegrenadines", "St Vincent"),
    ("sakartvelo", "Georgia"),
    ("salvador", "El Salvador"),
    ("samo", "Samoa"),
    ("samoa i sisifo", "Samoa"),
    ("samoaisisifo", "Samoa"),
    ("sanmarino", "San Marino"),
    ("sao thome e principe", "Sao Tome and Principe"),
    ("sao tome e principe", "Sao Tome and Principe"),
    ("saothomeeprincipe", "Sao Tome and Principe"),
    ("saotomeandprincipe", "Sao Tome and Principe"),
    ("saotomeeprincipe", "Sao Tome and Principe"),
    ("sarnam sranangron", "Suriname"),
    ("sarnam", "Suriname"),
    ("sarnamsranangron", "Suriname"),
    ("saudiarabia", "Saudi Arabia"),
    ("sb", "Solomon Islands"),
    ("sc", "Seychelles"),
    ("schweiz", "Switzerland"),
    ("sd", "Sudan"),
    ("se", "Sweden"),
    ("sesel", "Seychelles"),
    ("sg", "Singapore"),
    ("shac", "Ascension"),
    ("shhl", "Saint Helena"),
    ("shqipëria", "Albania"),
    ("shta", "Tristan da Cunha"),
    ("si", "Slovenia"),
    ("siam", "Thailand"),
    ("sierraleone", "Sierra Leone"),
    ("singapur", "Singapore"),
    ("singapura", "Singapore"),
    ("sint maarten", "Sint Maarten (Dutch part)"),
    ("sinteustatius", "Sint Eustatius"),
    ("sintmaarten", "Sint Maarten (Dutch part)"),
    ("sintmaarten(dutchpart)", "Sint Maarten (Dutch part)"),
    ("sion", "Israel"),
    ("sj", "Svalbard and Jan Mayen"),
    ("sk", "Slovakia"),
    ("sl", "Sierra Leone"),
    ("slovak republic", "Slovakia"),
    ("slovakrepublic", "Slovakia"),
    ("slovenija", "Slovenia"),
    ("slovensko", "Slovakia"),
    ("slovenská", "Slovakia"),
    ("sm", "San Marino"),
    ("sn", "Senegal"),
    ("so", "Somalia"),
    ("socialist republic of vietnam", "Vietnam"),
    ("socialistrepublicofvietnam", "Vietnam"),
    ("solomon aelan", "Solomon Islands"),
    ("solomonaelan", "Solomon Islands"),
    ("solomonislands", "Solomon Islands"),
    ("solomons", "Solomon Islands"),
    ("soomaaliya", "Somalia"),
    ("soudan", "Sudan"),
    (
        "south georgia and the south sandwich islands",
        "South Georgia and South Sandwich Islands",
    ),
    ("south west africa", "Namibia"),
    ("southafrica", "South Africa"),
    ("southgeorgiaandsouthsandwichislands", "South Georgia and South Sandwich Islands"),
    (
        "southgeorgiaandthesouthsandwichislands",
        "South Georgia and South Sandwich Islands",
    ),
    ("southkorea", "South Korea"),
    ("southsudan", "South Sudan"),
    ("southwestafrica", "Namibia"),
    ("sovereign base areas of akrotiri and dhekelia", "Dhekelia"),
    ("sovereignbaseareasofakrotirianddhekelia", "Dhekelia"),
    ("spanish guinea", "Equatorial Guinea"),
    ("spanishguinea", "Equatorial Guinea"),
    ("sr", "Suriname"),
    ("sranangron", "Suriname"),
    ("srbija", "Serbia"),
    ("sri lankā", "Sri Lanka"),
    ("srilanka", "Sri Lanka"),
    ("srilankā", "Sri Lanka"),
    ("ss", "South Sudan"),
    ("st barth", "Saint Barthélemy"),
    ("st barthelemy", "Saint Barthélemy"),
    ("st thomas and principe", "Sao Tome and Principe"),
    ("st", "Sao Tome and Principe"),
    ("state of bahrain", "Bahrain"),
    ("state of eritrea", "Eritrea"),
    ("state of israel", "Israel"),
    ("state of kuwait", "Kuwait"),
    ("state of qatar", "Qatar"),
    ("stateofbahrain", "Bahrain"),
    ("stateoferitrea", "Eritrea"),
    ("stateofisrael", "Israel"),
    ("stateofkuwait", "Kuwait"),
    ("stateofqatar", "Qatar"),
    ("stbarth", "Saint Barthélemy"),
    ("stbarthelemy", "Saint Barthélemy"),
    ("stkittsandnevis", "St Kitts and Nevis"),
    ("stlucia", "St Lucia"),
    ("stthomasandprincipe", "Sao Tome and Principe"),
    ("stvincent", "St Vincent"),
    ("suidafrika", "South Africa"),
    ("suisse", "Switzerland"),
    ("sultanate of oman", "Oman"),
    ("sultanateofoman", "Oman"),
    ("suomi", "Finland"),
    ("suriyah", "Syria"),
    ("sv", "El Salvador"),
    ("svalbardandjanmayen", "Svalbard and Jan Mayen"),
    ("sverige", "Sweden"),
    ("svizra", "Switzerland"),
    ("svizzera", "Switzerland"),
    ("swatini", "Eswatini"),
    ("swiss confederation", "Switzerland"),
    ("swissconfederation", "Switzerland"),
    ("switerland", "Switzerland"),
    ("sx", "Sint Maarten (Dutch part)"),
    ("sy", "Syria"),
    ("syrian arab republic", "Syria"),
    ("syrianarabrepublic", "Syria"),
    ("sz", "Eswatini"),
    ("são tomé e príncipe", "Sao Tome and Principe"),
    ("sãotoméepríncipe", "Sao Tome and Principe"),
    ("sénégal", "Senegal"),
    ("tadzhik", "Tajikistan"),
    ("tadzhikistan", "Tajikistan"),
    ("tajik", "Tajikistan"),
    ("tc", "Turks and Caicos Islands"),
    ("tchad", "Chad"),
    ("td", "Chad"),
    ("territory of american samoa", "American Samoa"),
    ("territory of christmas island", "Christmas Island"),
    ("territory of guam", "Guam"),
    (
        "territory of heard island and mcdonald islands",
        "Heard Island and McDonald Islands",
    ),
    ("territory of norfolk island", "Norfolk Island"),
    ("territory of the cocos (keeling) islands", "Cocos (Keeling) Islands"),
    ("territory of the wallis and futuna islands", "Wallis and Futuna"),
    ("territoryofamericansamoa", "American Samoa"),
    ("territoryofchristmasisland", "Christmas Island"),
    ("territoryofguam", "Guam"),
    ("territoryofheardislandandmcdonaldislands", "Heard Island and McDonald Islands"),
    ("territoryofnorfolkisland", "Norfolk Island"),
    ("territoryofthecocos(keeling)islands", "Cocos (Keeling) Islands"),
    ("territoryofthewallisandfutunaislands", "Wallis and Futuna"),
    ("tf", "French Southern Territories"),
    ("tg", "Togo"),
    ("th", "Thailand"),
    ("the arab republic of egypt", "Egypt"),
    ("the argentine republic", "Argentina"),
    ("the bolivarian republic of venezuela", "Venezuela"),
    ("the british indian ocean territory", "British Indian Ocean Territory"),
    ("the central african republic", "Central African Republic"),
    ("the commonwealth of australia", "Australia"),
    ("the commonwealth of dominica", "Dominica"),
    ("the commonwealth of the bahamas", "The Bahamas"),
    ("the cooperative republic of guyana", "Guyana"),
    ("the czech republic", "Czechia"),
    ("the democratic republic of sao tome and principe", "Sao Tome and Principe"),
    ("the democratic republic of the congo", "Congo (Democratic Republic)"),
    ("the democratic republic of timorleste", "East Timor"),
    ("the democratic socialist republic of sri lanka", "Sri Lanka"),
    ("the dominican republic", "Dominican Republic"),
    ("the federal democratic republic of ethiopia", "Ethiopia"),
    ("the federal democratic republic of nepal", "Nepal"),
    ("the federal republic of germany", "Germany"),
    ("the federal republic of nigeria", "Nigeria"),
    ("the federated states of micronesia", "Micronesia"),
    ("the federation of saint christopher and nevis", "St Kitts and Nevis"),
    ("the federative republic of brazil", "Brazil"),
    ("the french republic", "France"),
    ("the gabonese republic", "Gabon"),
    ("the grand duchy of luxembourg", "Luxembourg"),
    ("the hashemite kingdom of jordan", "Jordan"),
    ("the hellenic republic", "Greece"),
    ("the independent state of papua new guinea", "Papua New Guinea"),
    ("the independent state of samoa", "Samoa"),
    ("the islamic republic of afghanistan", "Afghanistan"),
    ("the islamic republic of iran", "Iran"),
    ("the islamic republic of mauritania", "Mauritania"),
    ("the islamic republic of pakistan", "Pakistan"),
    ("the italian republic", "Italy"),
    ("the kingdom of bahrain", "Bahrain"),
    ("the kingdom of belgium", "Belgium"),
    ("the kingdom of bhutan", "Bhutan"),
    ("the kingdom of cambodia", "Cambodia"),
    ("the kingdom of denmark", "Denmark"),
    ("the kingdom of lesotho", "Lesotho"),
    ("the kingdom of morocco", "Morocco"),
    ("the kingdom of norway", "Norway"),
    ("the kingdom of saudi arabia", "Saudi Arabia"),
    ("the kingdom of spain", "Spain"),
    ("the kingdom of swaziland", "Eswatini"),
    ("the kingdom of sweden", "Sweden"),
    ("the kingdom of thailand", "Thailand"),
    ("the kingdom of the netherlands", "Netherlands"),
    ("the kingdom of tonga", "Tonga"),
    ("the kyrgyz republic", "Kyrgyzstan"),
    ("the lebanese republic", "Lebanon"),
    ("the occupied palestinian territories", "Occupied Palestinian Territories"),
    ("the oriental republic of uruguay", "Uruguay"),
    ("the plurinational state of bolivia", "Bolivia"),
    ("the portuguese republic", "Portugal"),
    ("the principality of andorra", "Andorra"),
    ("the principality of liechtenstein", "Liechtenstein"),
    ("the principality of monaco", "Monaco"),
    ("the republic of albania", "Albania"),
    ("the republic of angola", "Angola"),
    ("the republic of armenia", "Armenia"),
    ("the republic of austria", "Austria"),
    ("the republic of azerbaijan", "Azerbaijan"),
    ("the republic of belarus", "Belarus"),
    ("the republic of benin", "Benin"),
    ("the republic of botswana", "Botswana"),
    ("the republic of bulgaria", "Bulgaria"),
    ("the republic of burundi", "Burundi"),
    ("the republic of cabo verde", "Cape Verde"),
    ("the republic of cameroon", "Cameroon"),
    ("the republic of chad", "Chad"),
    ("the republic of chile", "Chile"),
    ("the republic of colombia", "Colombia"),
    ("the republic of costa rica", "Costa Rica"),
    ("the republic of croatia", "Croatia"),
    ("the republic of cuba", "Cuba"),
    ("the republic of cyprus", "Cyprus"),
    ("the republic of djibouti", "Djibouti"),
    ("the republic of ecuador", "Ecuador"),
    ("the republic of el salvador", "El Salvador"),
    ("the republic of equatorial guinea", "Equatorial Guinea"),
    ("the republic of estonia", "Estonia"),
    ("the republic of fiji", "Fiji"),
    ("the republic of finland", "Finland"),
    ("the republic of ghana", "Ghana"),
    ("the republic of guatemala", "Guatemala"),
    ("the republic of guinea", "Guinea"),
    ("the republic of guineabissau", "Guinea-Bissau"),
    ("the republic of haiti", "Haiti"),
    ("the republic of honduras", "Honduras"),
    ("the republic of iceland", "Iceland"),
    ("the republic of india", "India"),
    ("the republic of indonesia", "Indonesia"),
    ("the republic of iraq", "Iraq"),
    ("the republic of kazakhstan", "Kazakhstan"),
    ("the republic of kenya", "Kenya"),
    ("the republic of kiribati", "Kiribati"),
    ("the republic of korea", "South Korea"),
    ("the republic of kosovo", "Kosovo"),
    ("the republic of latvia", "Latvia"),
    ("the republic of liberia", "Liberia"),
    ("the republic of lithuania", "Lithuania"),
    ("the republic of macedonia", "North Macedonia"),
    ("the republic of madagascar", "Madagascar"),
    ("the republic of malawi", "Malawi"),
    ("the republic of maldives", "Maldives"),
    ("the republic of mali", "Mali"),
    ("the republic of malta", "Malta"),
    ("the republic of mauritius", "Mauritius"),
    ("the republic of moldova", "Moldova"),
    ("the republic of mozambique", "Mozambique"),
    ("the republic of namibia", "Namibia"),
    ("the republic of nauru", "Nauru"),
    ("the republic of nicaragua", "Nicaragua"),
    ("the republic of niger", "Niger"),
    ("the republic of palau", "Palau"),
    ("the republic of panama", "Panama"),
    ("the republic of paraguay", "Paraguay"),
    ("the republic of peru", "Peru"),
    ("the republic of poland", "Poland"),
    ("the republic of rwanda", "Rwanda"),
    ("the republic of san marino", "San Marino"),
    ("the republic of senegal", "Senegal"),
    ("the republic of serbia", "Serbia"),
    ("the republic of seychelles", "Seychelles"),
    ("the republic of sierra leone", "Sierra Leone"),
    ("the republic of singapore", "Singapore"),
    ("the republic of slovenia", "Slovenia"),
    ("the republic of south africa", "South Africa"),
    ("the republic of south sudan", "South Sudan"),
    ("the republic of suriname", "Suriname"),
    ("the republic of tajikistan", "Tajikistan"),
    ("the republic of the congo", "Congo"),
    ("the republic of the gambia", "The Gambia"),
    ("the republic of the marshall islands", "Marshall Islands"),
    ("the republic of the philippines", "Philippines"),
    ("the republic of the sudan", "Sudan"),
    ("the republic of the union of myanmar", "Myanmar (Burma)"),
    ("the republic of trinidad and tobago", "Trinidad and Tobago"),
    ("the republic of turkey", "Turkey"),
    ("the republic of uganda", "Uganda"),
    ("the republic of uzbekistan", "Uzbekistan"),
    ("the republic of vanuatu", "Vanuatu"),
    ("the republic of yemen", "Yemen"),
    ("the republic of zambia", "Zambia"),
    ("the republic of zimbabwe", "Zimbabwe"),
    ("the russian federation", "Russia"),
    ("the slovak republic", "Slovakia"),
    ("the socialist republic of vietnam", "Vietnam"),
    ("the state of eritrea", "Eritrea"),
    ("the state of israel", "Israel"),
    ("the state of kuwait", "Kuwait"),
    ("the state of qatar", "Qatar"),
    ("the states", "United States"),
    ("the sultanate of oman", "Oman"),
    ("the swiss confederation", "Switzerland"),
    ("the syrian arab republic", "Syria"),
    ("the togolese republic", "Togo"),
    ("the tunisian republic", "Tunisia"),
    ("the union of the comoros", "Comoros"),
    ("the united arab emirates", "United Arab Emirates"),
    ("the united mexican states", "Mexico"),
    ("the united republic of tanzania", "Tanzania"),
    ("the united states of america", "United States"),
    ("the virgin islands", "British Virgin Islands"),
    ("thearabrepublicofegypt", "Egypt"),
    ("theargentinerepublic", "Argentina"),
    ("thebahamas", "The Bahamas"),
    ("thebolivarianrepublicofvenezuela", "Venezuela"),
    ("thebritishindianoceanterritory", "British Indian Ocean Territory"),
    ("thecentralafricanrepublic", "Central African Republic"),
    ("thecommonwealthofaustralia", "Australia"),
    ("thecommonwealthofdominica", "Dominica"),
    ("thecommonwealthofthebahamas", "The Bahamas"),
    ("thecooperativerepublicofguyana", "Guyana"),
    ("theczechrepublic", "Czechia"),
    ("thedemocraticrepublicofsaotomeandprincipe", "Sao Tome and Principe"),
    ("thedemocraticrepublicofthecongo", "Congo (Democratic Republic)"),
    ("thedemocraticrepublicoftimorleste", "East Timor"),
    ("thedemocraticsocialistrepublicofsrilanka", "Sri Lanka"),
    ("thedominicanrepublic", "Dominican Republic"),
    ("thefederaldemocraticrepublicofethiopia", "Ethiopia"),
    ("thefederaldemocraticrepublicofnepal", "Nepal"),
    ("thefederalrepublicofgermany", "Germany"),
    ("thefederalrepublicofnigeria", "Nigeria"),
    ("thefederatedstatesofmicronesia", "Micronesia"),
    ("thefederationofsaintchristopherandnevis", "St Kitts and Nevis"),
    ("thefederativerepublicofbrazil", "Brazil"),
    ("thefrenchrepublic", "France"),
    ("thegaboneserepublic", "Gabon"),
    ("thegambia", "The Gambia"),
    ("thegrandduchyofluxembourg", "Luxembourg"),
    ("thehashemitekingdomofjordan", "Jordan"),
    ("thehellenicrepublic", "Greece"),
    ("theindependentstateofpapuanewguinea", "Papua New Guinea"),
    ("theindependentstateofsamoa", "Samoa"),
    ("theislamicrepublicofafghanistan", "Afghanistan"),
    ("theislamicrepublicofiran", "Iran"),
    ("theislamicrepublicofmauritania", "Mauritania"),
    ("theislamicrepublicofpakistan", "Pakistan"),
    ("theitalianrepublic", "Italy"),
    ("thekingdomofbahrain", "Bahrain"),
    ("thekingdomofbelgium", "Belgium"),
    ("thekingdomofbhutan", "Bhutan"),
    ("thekingdomofcambodia", "Cambodia"),
    ("thekingdomofdenmark", "Denmark"),
    ("thekingdomoflesotho", "Lesotho"),
    ("thekingdomofmorocco", "Morocco"),
    ("thekingdomofnorway", "Norway"),
    ("thekingdomofsaudiarabia", "Saudi Arabia"),
    ("thekingdomofspain", "Spain"),
    ("thekingdomofswaziland", "Eswatini"),
    ("thekingdomofsweden", "Sweden"),
    ("thekingdomofthailand", "Thailand"),
    ("thekingdomofthenetherlands", "Netherlands"),
    ("thekingdomoftonga", "Tonga"),
    ("thekyrgyzrepublic", "Kyrgyzstan"),
    ("thelebaneserepublic", "Lebanon"),
    ("theoccupiedpalestinianterritories", "Occupied Palestinian Territories"),
    ("theorientalrepublicofuruguay", "Uruguay"),
    ("theplurinationalstateofbolivia", "Bolivia"),
    ("theportugueserepublic", "Portugal"),
    ("theprincipalityofandorra", "Andorra"),
    ("theprincipalityofliechtenstein", "Liechtenstein"),
    ("theprincipalityofmonaco", "Monaco"),
    ("therepublicofalbania", "Albania"),
    ("therepublicofangola", "Angola"),
    ("therepublicofarmenia", "Armenia"),
    ("therepublicofaustria", "Austria"),
    ("therepublicofazerbaijan", "Azerbaijan"),
    ("therepublicofbelarus", "Belarus"),
    ("therepublicofbenin", "Benin"),
    ("therepublicofbotswana", "Botswana"),
    ("therepublicofbulgaria", "Bulgaria"),
    ("therepublicofburundi", "Burundi"),
    ("therepublicofcaboverde", "Cape Verde"),
    ("therepublicofcameroon", "Cameroon"),
    ("therepublicofchad", "Chad"),
    ("therepublicofchile", "Chile"),
    ("therepublicofcolombia", "Colombia"),
    ("therepublicofcostarica", "Costa Rica"),
    ("therepublicofcroatia", "Croatia"),
    ("therepublicofcuba", "Cuba"),
    ("therepublicofcyprus", "Cyprus"),
    ("therepublicofdjibouti", "Djibouti"),
    ("therepublicofecuador", "Ecuador"),
    ("therepublicofelsalvador", "El Salvador"),
    ("therepublicofequatorialguinea", "Equatorial Guinea"),
    ("therepublicofestonia", "Estonia"),
    ("therepublicoffiji", "Fiji"),
    ("therepublicoffinland", "Finland"),
    ("therepublicofghana", "Ghana"),
    ("therepublicofguatemala", "Guatemala"),
    ("therepublicofguinea", "Guinea"),
    ("therepublicofguineabissau", "Guinea-Bissau"),
    ("therepublicofhaiti", "Haiti"),
    ("therepublicofhonduras", "Honduras"),
    ("therepublicoficeland", "Iceland"),
    ("therepublicofindia", "India"),
    ("therepublicofindonesia", "Indonesia"),
    ("therepublicofiraq", "Iraq"),
    ("therepublicofkazakhstan", "Kazakhstan"),
    ("therepublicofkenya", "Kenya"),
    ("therepublicofkiribati", "Kiribati"),
    ("therepublicofkorea", "South Korea"),
    ("therepublicofkosovo", "Kosovo"),
    ("therepublicoflatvia", "Latvia"),
    ("therepublicofliberia", "Liberia"),
    ("therepublicoflithuania", "Lithuania"),
    ("therepublicofmacedonia", "North Macedonia"),
    ("therepublicofmadagascar", "Madagascar"),
    ("therepublicofmalawi", "Malawi"),
    ("therepublicofmaldives", "Maldives"),
    ("therepublicofmali", "Mali"),
    ("therepublicofmalta", "Malta"),
    ("therepublicofmauritius", "Mauritius"),
    ("therepublicofmoldova", "Moldova"),
    ("therepublicofmozambique", "Mozambique"),
    ("therepublicofnamibia", "Namibia"),
    ("therepublicofnauru", "Nauru"),
    ("therepublicofnicaragua", "Nicaragua"),
    ("therepublicofniger", "Niger"),
    ("therepublicofpalau", "Palau"),
    ("therepublicofpanama", "Panama"),
    ("therepublicofparaguay", "Paraguay"),
    ("therepublicofperu", "Peru"),
    ("therepublicofpoland", "Poland"),
    ("therepublicofrwanda", "Rwanda"),
    ("therepublicofsanmarino", "San Marino"),
    ("therepublicofsenegal", "Senegal"),
    ("therepublicofserbia", "Serbia"),
    ("therepublicofseychelles", "Seychelles"),
    ("therepublicofsierraleone", "Sierra Leone"),
    ("therepublicofsingapore", "Singapore"),
    ("therepublicofslovenia", "Slovenia"),
    ("therepublicofsouthafrica", "South Africa"),
    ("therepublicofsouthsudan", "South Sudan"),
    ("therepublicofsuriname", "Suriname"),
    ("therepublicoftajikistan", "Tajikistan"),
    ("therepublicofthecongo", "Congo"),
    ("therepublicofthegambia", "The Gambia"),
    ("therepublicofthemarshallislands", "Marshall Islands"),
    ("therepublicofthephilippines", "Philippines"),
    ("therepublicofthesudan", "Sudan"),
    ("therepublicoftheunionofmyanmar", "Myanmar (Burma)"),
    ("therepublicoftrinidadandtobago", "Trinidad and Tobago"),
    ("therepublicofturkey", "Turkey"),
    ("therepublicofuganda", "Uganda"),
    ("therepublicofuzbekistan", "Uzbekistan"),
    ("therepublicofvanuatu", "Vanuatu"),
    ("therepublicofyemen", "Yemen"),
    ("therepublicofzambia", "Zambia"),
    ("therepublicofzimbabwe", "Zimbabwe"),
    ("therussianfederation", "Russia"),
    ("theslovakrepublic", "Slovakia"),
    ("thesocialistrepublicofvietnam", "Vietnam"),
    ("thestateoferitrea", "Eritrea"),
    ("thestateofisrael", "Israel"),
    ("thestateofkuwait", "Kuwait"),
    ("thestateofqatar", "Qatar"),
    ("thestates", "United States"),
    ("thesultanateofoman", "Oman"),
    ("theswissconfederation", "Switzerland"),
    ("thesyrianarabrepublic", "Syria"),
    ("thetogoleserepublic", "Togo"),
    ("thetunisianrepublic", "Tunisia"),
    ("theunionofthecomoros", "Comoros"),
    ("theunitedarabemirates", "United Arab Emirates"),
    ("theunitedmexicanstates", "Mexico"),
    ("theunitedrepublicoftanzania", "Tanzania"),
    ("theunitedstatesofamerica", "United States"),
    ("thevirginislands", "British Virgin Islands"),
    ("timorleste", "East Timor"),
    ("tj", "Tajikistan"),
    ("tk", "Tokelau"),
    ("tl", "East Timor"),
    ("tm", "Turkmenistan"),
    ("tn", "Tunisia"),
    ("to", "Tonga"),
    ("togolese republic", "Togo"),
    ("togolese", "Togo"),
    ("togoleserepublic", "Togo"),
    ("tojikistan", "Tajikistan"),
    ("toçikiston", "Tajikistan"),
    ("tr", "Turkey"),
    ("trinidadandtobago", "Trinidad and Tobago"),
    ("tristandacunha", "Tristan da Cunha"),
    ("tt", "Trinidad and Tobago"),
    ("tunes", "Tunisia"),
    ("tunisian republic", "Tunisia"),
    ("tunisianrepublic", "Tunisia"),
    ("turkiye", "Turkey"),
    ("turkmen", "Turkmenistan"),
    ("turkmenia", "Turkmenistan"),
    ("turkomen", "Turkmenistan"),
    ("turksandcaicosislands", "Turks and Caicos Islands"),
    ("tv", "Tuvalu"),
    ("tw", "Taiwan"),
    ("tz", "Tanzania"),
    ("táiwān", "Taiwan"),
    ("türkiye", "Turkey"),
    ("türkmenistan", "Turkmenistan"),
    ("tšād", "Chad"),
    ("tūns", "Tunisia"),
    ("ua", "Ukraine"),
    ("uae", "United Arab Emirates"),
    ("ug", "Uganda"),
    ("ukrayina", "Ukraine"),
    ("ukraїna", "Ukraine"),
    ("umbuso weswatini", "Eswatini"),
    ("umbusoweswatini", "Eswatini"),
    ("ummalquwain", "Umm al-Quwain"),
    ("umzantsi afrika", "South Africa"),
    ("umzantsiafrika", "South Africa"),
    ("union of the comoros", "Comoros"),
    ("unionofthecomoros", "Comoros"),
    ("unit states", "United States"),
    ("unite states", "United States"),
    ("united arab republic", "Egypt"),
    ("united mexican states", "Mexico"),
    ("united republic of tanzania", "Tanzania"),
    ("united sat", "United States"),
    ("united staes", "United States"),
    ("united stated", "United States"),
    ("united states america", "United States"),
    ("united states of america", "United States"),
    ("united stats", "United States"),
    ("united sttes", "United States"),
    ("unitedarabemirates", "United Arab Emirates"),
    ("unitedarabrepublic", "Egypt"),
    ("unitedmexicanstates", "Mexico"),
    ("unitedrepublicoftanzania", "Tanzania"),
    ("unitedsat", "United States"),
    ("unitedstaes", "United States"),
    ("unitedstated", "United States"),
    ("unitedstates", "United States"),
    ("unitedstatesofamerica", "United States"),
    ("unitedstatesvirginislands", "United States Virgin Islands"),
    ("unitedstats", "United States"),
    ("unitedsttes", "United States"),
    ("unites states", "United States"),
    ("unitesstates", "United States"),
    ("unitestates", "United States"),
    ("unitstates", "United States"),
    ("untied state", "United States"),
    ("untiedstate", "United States"),
    ("us", "United States"),
    ("usa", "United States"),
    ("uvea mo futuna", "Wallis and Futuna"),
    ("uveamofutuna", "Wallis and Futuna"),
    ("uy", "Uruguay"),
    ("uz", "Uzbekistan"),
    ("uzbek", "Uzbekistan"),
    ("va", "Vatican City"),
    ("vatican city state", "Vatican City"),
    ("vaticancity", "Vatican City"),
    ("vaticancitystate", "Vatican City"),
    ("vc", "St Vincent"),
    ("ve", "Venezuela"),
    ("veitnam", "Vietnam"),
    ("venezula", "Venezuela"),
    ("vg", "British Virgin Islands"),
    ("vi", "United States Virgin Islands"),
    ("vietman", "Vietnam"),
    ("virgin islands of the united states", "United States Virgin Islands"),
    ("virgin islands", "British Virgin Islands"),
    ("virgina islands", "British Virgin Islands"),
    ("virginaislands", "British Virgin Islands"),
    ("virginislands", "British Virgin Islands"),
    ("virginislandsoftheunitedstates", "United States Virgin Islands"),
    ("viti", "Fiji"),
    ("việt nam", "Vietnam"),
    ("việtnam", "Vietnam"),
    ("vn", "Vietnam"),
    ("volta", "Burkina Faso"),
    ("volívia", "Bolivia"),
    ("vu", "Vanuatu"),
    ("wakeisland", "Wake Island"),
    ("wallisandfutuna", "Wallis and Futuna"),
    ("wallisetfutuna", "Wallis and Futuna"),
    ("west pakistan", "Pakistan"),
    ("western samoa", "Samoa"),
    ("westernsahara", "Western Sahara"),
    ("westernsamoa", "Samoa"),
    ("westpakistan", "Pakistan"),
    ("weswatini swatini ngwane", "Eswatini"),
    ("weswatini", "Eswatini"),
    ("weswatiniswatiningwane", "Eswatini"),
    ("wf", "Wallis and Futuna"),
    ("white russia", "Belarus"),
    ("whiterussia", "Belarus"),
    ("ws", "Samoa"),
    ("wuliwya", "Bolivia"),
    ("xk", "Kosovo"),
    ("xqz", "Akrotiri"),
    ("xxd", "Dhekelia"),
    ("xīnjiāpō", "Singapore"),
    ("yaltopya", "Ethiopia"),
    ("ye", "Yemen"),
    ("yisrael", "Israel"),
    ("yt", "Mayotte"),
    ("za", "South Africa"),
    ("zealnd", "New Zealand"),
    ("zeland", "New Zealand"),
    ("zhongguo", "China"),
    ("zhonghua peoples republic", "China"),
    ("zhonghua", "China"),
    ("zhonghuapeoplesrepublic", "China"),
    ("zhōngguó", "China"),
    ("zhōnghuá mínguó", "Taiwan"),
    ("zhōnghuámínguó", "Taiwan"),
    ("zion", "Israel"),
    ("zm", "Zambia"),
    ("ztate of katar", "Qatar"),
    ("ztateofkatar", "Qatar"),
    ("zw", "Zimbabwe"),
    ("åland", "Åland Islands"),
    ("ålandislands", "Åland Islands"),
    ("éire", "Ireland"),
    ("étatsunis", "United States"),
    ("ísland", "Iceland"),
    ("îraq", "Iraq"),
    ("österreich", "Austria"),
    ("česko", "Czechia"),
    ("česká republika", "Czechia"),
    ("česká", "Czechia"),
    ("českárepublika", "Czechia"),
    ("īrān", "Iran"),
    ("ελλάδα", "Greece"),
    ("ελλάς", "Greece"),
    ("κύπρος", "Cyprus"),
    ("беларусь", "Belarus"),
    ("босна и херцеговина", "Bosnia and Herzegovina"),
    ("боснаихерцеговина", "Bosnia and Herzegovina"),
    ("българия", "Bulgaria"),
    ("казахстан", "Kazakhstan"),
    ("киргизия", "Kyrgyzstan"),
    ("косово", "Kosovo"),
    ("кыргызстан", "Kyrgyzstan"),
    ("македонија", "North Macedonia"),
    ("монгол улс", "Mongolia"),
    ("монголулс", "Mongolia"),
    ("российская", "Russia"),
    ("россия", "Russia"),
    ("србија srbija", "Serbia"),
    ("србија", "Serbia"),
    ("србијаsrbija", "Serbia"),
    ("тоҷикистон", "Tajikistan"),
    ("україна", "Ukraine"),
    ("црна гора", "Montenegro"),
    ("црнагора", "Montenegro"),
    ("ўзбекистон", "Uzbekistan"),
    ("қазақстан", "Kazakhstan"),
    ("հայաստան", "Armenia"),
    ("ישראל", "Israel"),
    ("إرتريا", "Eritrea"),
    ("إسرائيل ישראל", "Israel"),
    ("إسرائيل", "Israel"),
    ("إسرائيلישראל", "Israel"),
    ("افغانستان", "Afghanistan"),
    ("الأردن", "Jordan"),
    ("الإمارات العربيّة المتّحدة", "United Arab Emirates"),
    ("الإمارات", "United Arab Emirates"),
    ("الإماراتالعربيّةالمتّحدة", "United Arab Emirates"),
    ("البحرين", "Bahrain"),
    ("الجزائر", "Algeria"),
    ("السعودية", "Saudi Arabia"),
    ("السودان", "Sudan"),
    ("الصومال", "Somalia"),
    ("العراق", "Iraq"),
    ("العراق\u200e", "Iraq"),
    ("الكويت", "Kuwait"),
    ("المغرب", "Morocco"),
    ("المملكة العربية السعودية", "Saudi Arabia"),
    ("المملكةالعربيةالسعودية", "Saudi Arabia"),
    ("الموريتانية", "Mauritania"),
    ("اليمن", "Yemen"),
    ("ایران", "Iran"),
    ("بروني", "Brunei"),
    ("تشاد", "Chad"),
    ("تشاد\u200e", "Chad"),
    ("تونس", "Tunisia"),
    ("جز القمر", "Comoros"),
    ("جزالقمر", "Comoros"),
    ("جزر القمر", "Comoros"),
    ("جزرالقمر", "Comoros"),
    ("جيبوتي", "Djibouti"),
    ("جيبوتي\u200e", "Djibouti"),
    ("دولة الكويت", "Kuwait"),
    ("دولةالكويت", "Kuwait"),
    ("سورية", "Syria"),
    ("عمان", "Oman"),
    ("عُمان", "Oman"),
    ("فلسطين", "Occupied Palestinian Territories"),
    ("قازاقستان", "Kazakhstan"),
    ("قطر", "Qatar"),
    ("لبنان", "Lebanon"),
    ("لصحراء الغربية", "Western Sahara"),
    ("لصحراءالغربية", "Western Sahara"),
    ("ليبيا", "Libya"),
    ("مصر", "Egypt"),
    ("موريتانيا", "Mauritania"),
    ("پاکستان", "Pakistan"),
    ("नेपाल", "Nepal"),
    ("फ़िजी", "Fiji"),
    ("भारत गणराज्य", "India"),
    ("भारत", "India"),
    ("भारतगणराज्य", "India"),
    ("भारतम्", "India"),
    ("भूटान", "Bhutan"),
    ("शर्नम्", "Suriname"),
    ("বাংলাদেশ", "Bangladesh"),
    ("ভারত", "India"),
    ("ভাৰত", "India"),
    ("ਭਾਰਤ", "India"),
    ("ભારત", "India"),
    ("ଭାରତ", "India"),
    ("இலங்கை", "Sri Lanka"),
    ("சிங்கப்பூர் குடியரசு", "Singapore"),
    ("சிங்கப்பூர்", "Singapore"),
    ("சிங்கப்பூர்கு", "Singapore"),
    ("சிங்கப்பூர்குடியரசு", "Singapore"),
    ("டியரசு", "Singapore"),
    ("பாரதம்", "India"),
    ("மலேசியா", "Malaysia"),
    ("భారత దేశం", "India"),
    ("భారతదేశం", "India"),
    ("ಭಾರತ", "India"),
    ("ഭാരതം", "India"),
    # ('ශ්රී ලංකා இலங்கை', 'Sri Lanka'),
    # ('ශ්රී ලංකා', 'Sri Lanka'),
    # ('ශ්රී ලංකාව', 'Sri Lanka'),
    # ('ශ්රීලංකා', 'Sri Lanka'),
    # ('ශ්රීලංකාஇலங்கை', 'Sri Lanka'),
    # ('ශ්රීලංකාව', 'Sri Lanka'),
    ("ประเทศไทย", "Thailand"),
    ("ราชอาณาจักรไทย", "Thailand"),
    ("เมืองไทย", "Thailand"),
    ("ປະເທດລາວ", "Laos"),
    ("འབྲུག་ཡུལ", "Bhutan"),
    ("မြန်မာ", "Myanmar (Burma)"),
    ("საქართველო", "Georgia"),
    ("ኢትዮጵያ", "Ethiopia"),
    ("ኤርትራ", "Eritrea"),
    ("កម្ពុជា", "Cambodia"),
    ("ᠮᠤᠩᠭᠤᠯ ᠤᠯᠤᠰ", "Mongolia"),
    ("ᠮᠤᠩᠭᠤᠯᠤᠯᠤᠰ", "Mongolia"),
    ("‘umān", "Oman"),
    ("ⴰⴳⴰⵡⵛ", "Mauritania"),
    ("ⴰⵎⵔⵔⵓⴽ", "Morocco"),
    ("ⴷⵣⴰⵢⴻⵔ", "Algeria"),
    ("ⵍⵉⴱⵢⴰ", "Libya"),
    ("ⵍⵎⵖⵔⵉⴱ", "Morocco"),
    ("ⵎⵓⵔⵉⵜⴰⵏ", "Mauritania"),
    ("ⵜⵓⵏⵙ", "Tunisia"),
    ("中华", "China"),
    ("中国", "China"),
    ("中国/中华", "China"),
    ("中華民國", "Taiwan"),
    ("台灣", "Taiwan"),
    ("新加坡", "Singapore"),
    ("新加坡共和国", "Singapore"),
    ("日本", "Japan"),
    ("臺灣", "Taiwan"),
    ("臺灣/台灣", "Taiwan"),
    ("香港", "Hong Kong"),
    ("马来西亚", "Malaysia"),
    ("남한", "South Korea"),
    ("북조선", "North Korea"),
    ("조선 / 朝鮮", "North Korea"),
    ("조선/朝鮮", "North Korea"),
    ("한국 / 韓國", "South Korea"),
    ("한국/韓國", "South Korea"),
)


CROWDSOURCED_MISTAKES = (
    ("burma", "Myanmar (Burma)", "rest-of-world"),
    ("canary islands", "Canary Islands", "europe"),
    ("czechoslovakia", "Czechia", "europe"),
    ("east germany", "Germany", "europe"),
    ("easter island", "Easter Island", "rest-of-world"),
    ("Eidal", "Italy", "europe"),
    ("falklands", "Falkland Islands", "rest-of-world"),
    ("Ffrainc", "France", "europe"),
    ("hawaii", "United States", "rest-of-world"),
    ("Herm", "United Kingdom", "united-kingdom"),
    ("Khazakhstan", "Kazakhstan", "europe"),
    ("korea", "South Korea", "rest-of-world"),
    ("macau", "Macao", "rest-of-world"),
    ("myanmar", "Myanmar (Burma)", "rest-of-world"),
    ("new zeeland", "New Zealand", "rest-of-world"),
    ("NI", "United Kingdom", "united-kingdom"),
    ("Pitcairn Island", "Pitcairn, Henderson, Ducie and Oeno Islands", "rest-of-world"),
    ("republic of china", "Taiwan", "rest-of-world"),
    ("Republik Österreich", "Austria", "europe"),
    ("République Islamique de Mauritanie", "Mauritania", "rest-of-world"),
    ("Mauritanie", "Mauritania", "rest-of-world"),
    ("Sark", "United Kingdom", "united-kingdom"),
    ("South Ireland", "Ireland", "europe"),
    ("St Helena", "Saint Helena", "rest-of-world"),
    ("Swaziland", "Eswatini", "rest-of-world"),
    ("the falkland islands", "Falkland Islands", "rest-of-world"),
    ("the falklands", "Falkland Islands", "rest-of-world"),
    (
        "the sandwich islands",
        "South Georgia and the South Sandwich Islands",
        "rest-of-world",
    ),
    ("South Georgia", "South Georgia and the South Sandwich Islands", "rest-of-world"),
    ("Tristan", "Tristan da Cunha", "rest-of-world"),
    ("ussr", None, None),
    ("USSR", None, None),
    ("союз советских социалистических республик", None, None),
    ("Vatican", "Vatican City", "europe"),
    ("West Germany", "Germany", "europe"),
    ("Yr Alban", "United Kingdom", "united-kingdom"),
    ("yugoslavia", None, None),
    ("jugoslavija", None, None),
    ("Swistir", "Switzerland", "europe"),
    ("Y Swistir", "Switzerland", "europe"),
    ("Saint Kitts", "St Kitts and Nevis", "rest-of-world"),
    ("St Kitts", "St Kitts and Nevis", "rest-of-world"),
)
