env: production
instances: 2
memory: 2G
command: newrelic-admin run-program gunicorn -c /home/vcap/app/gunicorn_config.py gunicorn_entry:application
public_admin_route: beta.notify.gov
cloud_dot_gov_route: notify.app.cloud.gov
redis_enabled: 1
nr_agent_id: '1050708682'
nr_app_id: '1050708682'
API_PUBLIC_URL: https://notify-api-production.app.cloud.gov
